#############################################################各个环境主yaml配置#############################################################################
#                                                                                                                                                        #
#                                   如需切换到其他环境或改写其他环境配置，请分别前往对应的环境配置文件修改，切勿以切换环境以外的任何目的修改本文件！                          #
#                                                                                                                                                        #
##########################################################################################################################################################

#如需全局修改某些配置，可以在此追加。主配置内的所有配置的优先级都高于相关环境的配置的优先级

#激活环境：当前激活：开发环境（dev）。
#参考环境列表：dev => 开发环境； prod =>生产环境 ； test => 测试环境
spring:
  profiles:
    active: dev